// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZRPAM3hvisulXycuCLvbFmnrpxDudxqU',
    appId: '1:557660823475:web:0aa7ca7e3cd49455a0b5c6',
    messagingSenderId: '557660823475',
    projectId: 'tppmnewsapp',
    authDomain: 'tppmnewsapp.firebaseapp.com',
    storageBucket: 'tppmnewsapp.appspot.com',
    measurementId: 'G-N6YHJGWHBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-La6yFdHV1IFI2HnL8AplSwEYtuW7V5g',
    appId: '1:557660823475:android:e02190272b00b1a3a0b5c6',
    messagingSenderId: '557660823475',
    projectId: 'tppmnewsapp',
    storageBucket: 'tppmnewsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkCv3dyBjG6rtMCxEGHjGF3IH0-4jyTM',
    appId: '1:557660823475:ios:b2a4c56aba7e698aa0b5c6',
    messagingSenderId: '557660823475',
    projectId: 'tppmnewsapp',
    storageBucket: 'tppmnewsapp.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDkCv3dyBjG6rtMCxEGHjGF3IH0-4jyTM',
    appId: '1:557660823475:ios:b2a4c56aba7e698aa0b5c6',
    messagingSenderId: '557660823475',
    projectId: 'tppmnewsapp',
    storageBucket: 'tppmnewsapp.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZRPAM3hvisulXycuCLvbFmnrpxDudxqU',
    appId: '1:557660823475:web:50a0d73e038520c3a0b5c6',
    messagingSenderId: '557660823475',
    projectId: 'tppmnewsapp',
    authDomain: 'tppmnewsapp.firebaseapp.com',
    storageBucket: 'tppmnewsapp.appspot.com',
    measurementId: 'G-QM81V9TWEP',
  );
}
